/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


/**
 *
 * @author USER
 */
public class studentDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        showDate.setText(dFormat.format(date));
        
        inputRollnum.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            filterAngka(evt);
             }
        });

        inputContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filterAngka(evt);
            }
        });
    }
    
    void clear(){
        inputRollnum.setText(""); // Roll Number
        inputName.setText(""); // Name
        inputGender.setSelectedIndex(0); // Gender
        inputEmail.setText(""); // Email
        inputContact.setText(""); // Contact Number
        inputAddress.setText(""); // Address
    }
    
    private void filterAngka(java.awt.event.KeyEvent evt) {
    char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // Abaikan input jika bukan angka
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showDate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputRollnum = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputContact = new javax.swing.JTextField();
        inputAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        inputGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainLabel.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        mainLabel.setText("Fill up the form");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Date: ");

        showDate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showDate.setText("time");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Roll Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Contact Number");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setText("Address");

        inputRollnum.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        inputRollnum.setForeground(new java.awt.Color(204, 204, 204));
        inputRollnum.setText("12345678");
        inputRollnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputRollnumFocusGained(evt);
            }
        });
        inputRollnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRollnumActionPerformed(evt);
            }
        });

        inputName.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        inputName.setForeground(new java.awt.Color(204, 204, 204));
        inputName.setText("John Doe");
        inputName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNameFocusGained(evt);
            }
        });

        inputEmail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(204, 204, 204));
        inputEmail.setText("john@upi.edu");
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
        });

        inputContact.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        inputContact.setForeground(new java.awt.Color(204, 204, 204));
        inputContact.setText("0812345678");
        inputContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputContactFocusGained(evt);
            }
        });

        inputAddress.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        inputAddress.setForeground(new java.awt.Color(204, 204, 204));
        inputAddress.setText("Kabupaten/Kota, Provinsi, Negara");
        inputAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputAddressFocusGained(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSave.setText("Save and Next");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        inputGender.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        inputGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        inputGender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputGenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputGenderFocusLost(evt);
            }
        });
        inputGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(mainLabel)
                        .addGap(185, 185, 185)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showDate)
                        .addGap(356, 356, 356)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel10))
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave)
                            .addComponent(inputRollnum)
                            .addComponent(inputName)
                            .addComponent(inputEmail)
                            .addComponent(inputContact)
                            .addComponent(inputAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                            .addComponent(inputGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(mainLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(showDate)
                            .addComponent(btnBack)
                            .addComponent(btnClose))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputRollnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(inputGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin akan keluar dari aplikasi?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void inputRollnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRollnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRollnumActionPerformed

    private void inputGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGenderActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String rollNo = inputRollnum.getText();
        String name = inputName.getText();
        String gender = (String) inputGender.getSelectedItem();
        String email = inputEmail.getText();
        String contactNo = inputContact.getText();
        String address = inputAddress.getText();
        String marks = "0";

        // Validasi apakah semua field sudah diisi
        StringBuilder errorMessage = new StringBuilder("Field berikut masih kosong atau belum diubah:\n");
        if (rollNo.isEmpty() || rollNo.equals("12345678")) errorMessage.append("- Roll Number\n");
        if (name.isEmpty() || name.equals("John Doe")) errorMessage.append("- Name\n");
        // Validasi untuk JComboBox bisa menggunakan getSelectedItem()
        if (email.isEmpty() || email.equals("john@upi.edu")) errorMessage.append("- Email\n");
        if (contactNo.isEmpty() || contactNo.equals("0812345678")) errorMessage.append("- Contact Number\n");
        if (address.isEmpty() || address.equals("Kabupaten/Kota, Provinsi, Negara")) errorMessage.append("- Address\n");

        if (errorMessage.length() > 52) { // 52 adalah panjang awal string validasi 
            JOptionPane.showMessageDialog(null, errorMessage.toString());
            return; // Hentikan proses jika ada field yang kosong atau belum diubah
        }
        
        try (Connection C = db_quizzapp.konfigDB();
             PreparedStatement psCheck = C.prepareStatement("SELECT COUNT(*) FROM students WHERE rollNo = ?");
             PreparedStatement psInsert = C.prepareStatement("INSERT INTO students VALUES (?, ?, ?, ?, ?, ?, ?)")) {

            psCheck.setString(1, rollNo);
            try (ResultSet rs = psCheck.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "Roll Number sudah Terdaftar!");
                    return; // Hentikan proses jika rollNo sudah ada
                }
            }

            psInsert.setString(1, rollNo);
            psInsert.setString(2, name);
            psInsert.setString(3, gender);
            psInsert.setString(4, email);
            psInsert.setString(5, contactNo);
            psInsert.setString(6, address);
            psInsert.setString(7, marks);
            psInsert.executeUpdate();

            JOptionPane.showMessageDialog(null, "Berhasil disimpan!");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void inputRollnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputRollnumFocusGained
        // TODO add your handling code here:
        if (inputRollnum.getText().equals("12345678")) {
            inputRollnum.setText("");
            inputRollnum.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputRollnumFocusGained

    private void inputNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNameFocusGained
        // TODO add your handling code here:
         if (inputName.getText().equals("John Doe")) {
            inputName.setText("");
            inputName.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputNameFocusGained

    private void inputGenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputGenderFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGenderFocusGained

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        // TODO add your handling code here:
        if (inputEmail.getText().equals("john@upi.edu")) {
           inputEmail.setText("");
           inputEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputContactFocusGained
        // TODO add your handling code here:
        if (inputContact.getText().equals("0812345678")) {
            inputContact.setText("");
            inputContact.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputContactFocusGained

    private void inputAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAddressFocusGained
        // TODO add your handling code here:
        if (inputAddress.getText().equals("Kabupaten/Kota, Provinsi, Negara")) {
            inputAddress.setText("");
            inputAddress.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputAddressFocusGained

    private void inputGenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputGenderFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGenderFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputContact;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JComboBox<String> inputGender;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputRollnum;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel showDate;
    // End of variables declaration//GEN-END:variables
}
